-- Your SQL goes here
DROP TABLE IF EXISTS sunlight CASCADE;
DROP TABLE IF EXISTS water CASCADE;
DROP TABLE IF EXISTS region CASCADE;
DROP TABLE IF EXISTS habitat CASCADE;
DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS plant CASCADE;